apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      serviceAccountName: mlflow
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: mlflow
          image: docker.io/hemaveeradhi/mlflow:amd64
          imagePullPolicy: IfNotPresent
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --backend-store-uri
            - postgresql://admin:admin@postgresql.$(NAMESPACE).svc.cluster.local:5432/db?sslmode=disable
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  type: ClusterIP
  selector:
    app: mlflow-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mlflow
spec:
  to:
    kind: Service
    name: mlflow-server
  port:
    targetPort: http
  tls:
    termination: edge
