---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: monitoring-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: pgsql-data
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel8/postgresql-13:1-101
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_USER
              value: admin
            - name: POSTGRESQL_PASSWORD
              value: admin
            - name: POSTGRESQL_DATABASE
              value: db
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data

          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1

          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - "--live"
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: monitoring-tools
spec:
  type: ClusterIP
  selector:
    name: postgresql
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-data
  namespace: monitoring-tools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: mcp-pf-fs-storageclass
  volumeMode: Filesystem
