apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-model
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 1
    model:
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-2b-instruct
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"

