apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlops-admin-redisns
  namespace: redisns        # ✅ ORA È NECESSARIO
subjects:
  - kind: User
    name: mlops-user
    apiGroup: rbac.authorization.k8s.io
