apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-model
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    openshift.io/display-name: granite-model
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"

spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: granite-runtime
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "1"
          memory: 4Gi
