apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  minio_root_user: minio
  minio_root_password: minio123
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
