apiVersion: batch/v1
kind: Job
metadata:
  name: create-redis-index
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-index
          image: redis:7.2        # 👈 solo redis-cli
          command: ["/bin/sh", "-c"]
          env:
            - name: REDIS_HOST
              value: my-doc.redis-mlops-user-a.svc.cluster.local
            - name: REDIS_PORT
              value: "14289"       # 👈 PORTA GIUSTA
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redb-my-doc
                  key: password
          args:
            - |
              set -e

              echo "Waiting for Redis..."
              until redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" ping | grep -q PONG; do
                sleep 3
              done

              echo "Creating vector index..."
              redis-cli -h "$REDIS_HOST" -p "$REDIS_PORT" -a "$REDIS_PASSWORD" <<'EOF'
              FT.CREATE idx:docs ON HASH PREFIX 1 doc: SCHEMA \
                page NUMERIC \
                source TEXT \
                content TEXT \
                content_vector VECTOR FLAT 6 \
                  TYPE FLOAT32 \
                  DIM 768 \
                  DISTANCE_METRIC COSINE
              EOF

              echo "Index created successfully"

