apiVersion: batch/v1
kind: Job
metadata:
  name: create-redis-index
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: redis-index
          image: redis/redis-stack-server:7.2.0-v9
          command: ["/bin/sh", "-c"]
          env:
            - name: REDIS_HOST
              value: my-doc
            - name: REDIS_PORT
              value: "16271"
          args:
            - |
              echo "Waiting for Redis..."
              until redis-cli -h $REDIS_HOST -p $REDIS_PORT ping; do
                sleep 3
              done

              echo "Creating vector index..."
              redis-cli -h $REDIS_HOST -p $REDIS_PORT <<EOF
              FT.CREATE idx:docs ON HASH PREFIX 1 doc: SCHEMA \
                page NUMERIC \
                source TEXT \
                content TEXT \
                content_vector VECTOR FLAT 6 \
                  TYPE FLOAT32 \
                  DIM 768 \
                  DISTANCE_METRIC COSINE
              EOF

              echo "Index created"
