apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-platform
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/acicfede/mlops-platform.git
    targetRevision: main
    path: argocd/app-of-apps/tenants

  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
