apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgresql
spec:
  type: ClusterIP
  selector:
    app: mlflow-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
