apiVersion: batch/v1
kind: Job
metadata:
  name: create-minio-buckets
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: quay.io/minio/mc:latest
          env:
            - name: MINIO_ENDPOINT
              value: http://minio-service:9000
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_password
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio "$MINIO_ENDPOINT" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb myminio/ml-workbench || true
              mc mb myminio/mlpipeline-artifacts || true
              mc mb myminio/guidellm-results || true
