apiVersion: v1
kind: Namespace
metadata:
  name: mlops-user-a
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/instance: mlops-user-a
    mlops.platform/tenant: user-a
