apiVersion: v1
kind: Namespace
metadata:
  name: mlops-user-b
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/instance: mlops-user-b
    mlops.platform/tenant: user-b
