apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-app-of-apps
  namespace: openshift-gitops
spec:
  project: mlops-platform
  source:
    repoURL: https://github.com/acicfede/mlops-platform.git
    targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

