apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-platform-core
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/acicfede/mlops-platform.git
    targetRevision: main
    path: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
