apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: granite-3-1-2b-instruct
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    openshift.io/display-name: granite-3.1-2b-instruct
  labels:
    networking.kserve.io/visibility: exposed
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    automountServiceAccountToken: false
    minReplicas: 1
    maxReplicas: 1
    model:
      modelFormat:
        name: vLLM
      runtime: granite-3-1-2b-instruct
      storageUri: oci://quay.io/redhat-ai-services/modelcar-catalog:granite-3.1-2b-instruct
      resources:
        requests:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
        limits:
          cpu: "1"
          memory: 4Gi
          nvidia.com/gpu: "1"
